### ISSUE TITLE
Listing buckets

### ISSUE THREAD

**Issue by jpds** [jeremychone/rust-ss3#4]
It should be possible to list buckets with this command, rather than returning an error:

```
ss3 ls s3://
```

**Comment by jeremychone** [comment]
Good request. Let me work on this. Might take a week depending of other work.

**Comment by jeremychone** [comment]
Implemented in `v0.1.0` and abo e.

**Comment by jpds** [comment]
`src/spath.rs` is still triggering a `NotValidS3Url`.

**Comment by jeremychone** [comment]
@jpds Yes, `spath` is not used when listing the buckets. The branching is upstream in the command. [cmd/mod.rs](https://github.com/jeremychone/rust-ss3/blob/main/src/cmd/mod.rs#L38)

Let me know if `ss3 ls s3://` does not work for you.

**Comment by jpds** [comment]
Apologies - I forgot to rebuild my `release` binary which was in my `$PATH` (had only done `debug` since the last release).
