### ISSUE TITLE
sync and rm operations

### ISSUE THREAD

**Issue by jpds** [jeremychone/rust-ss3#5]
I'd really like to use this tool over the normal `awscli` Python based however, two operations that are missing are the `sync` and `rm` file operations.

**Comment by jeremychone** [comment]
@jpds Good, request, i am going to create two sub tickets as the `rm` can be done relatively quickly, and the `sync` is more involved.

**Comment by jeremychone** [comment]
Ok, this ticket has been chopped into #7 for rm, and #8 for sync. Closing this one.
